### PR TITLE
#347 - Update NOTICE to take Apache license into account

### LINKED ISSUE #347: license declared in NOTICE.md missing Apache-2.0 (or: some files have wrong license headers)
During package review for fedora, a discrepancy between NOTICE.md SPDX identifier (EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0) and the files actually contained in the repo came up.

There's a bunch of files that still have Apache-2.0 license headers. Either those have not been fixed after the project was relicensed, or the SPDX identifier needs to be adapted to (EPL-2.0 OR GPL-2.0 WITH Classpath-exception 2.0) AND Apache-2.0.

Attached below is the list of files with Apache-2.0 license headers:

    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/Filter.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/FilterChain.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/FilterConfig.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/GenericServlet.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/LocalStrings.properties: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/LocalStrings_fr.properties: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/LocalStrings_ja.properties: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/RequestDispatcher.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/Servlet.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletConfig.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletContext.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletContextAttributeEvent.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletContextAttributeListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletContextEvent.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletContextListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletException.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletInputStream.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletOutputStream.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletRequest.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletRequestAttributeEvent.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletRequestAttributeListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletRequestEvent.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletRequestListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletRequestWrapper.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletResponse.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/ServletResponseWrapper.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/SingleThreadModel.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/UnavailableException.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/package.html: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/Cookie.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpServlet.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpServletRequest.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpServletRequestWrapper.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpServletResponse.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpServletResponseWrapper.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSession.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSessionActivationListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSessionAttributeListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSessionBindingEvent.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSessionBindingListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSessionContext.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSessionEvent.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpSessionListener.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/HttpUtils.java: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/LocalStrings.properties: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/LocalStrings_es.properties: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/LocalStrings_fr.properties: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/LocalStrings_ja.properties: Apache License 2.0
    ./servlet-api-5.0.0-RELEASE/api/src/main/java/jakarta/servlet/http/package.html: Apache License 2.0

### PR DESCRIPTION
**Pull request by arjantijms**
Fixes #347

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
Cc @waynebeaton @ivargrimstad

**Comment by edbratt** [comment]
I have no objection to this but has EMO license review approved this? Do 
they need to?

**Comment by arjantijms** [comment]
> I have no objection to this but has EMO license review approved this? 

Yes, this came out of an email exchange to EMO where @waynebeaton responded:

```
Your addition to the notice file should do the job nicely.

Specifically:

Portions of this program and the accompanying materials are made available under the terms of the Apache License, version 2.0 which is available at https://www.apache.org/licenses/LICENSE-2.0.
SPDX-License-Identifier: (EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0) AND Apache-2.0

Please include this with the license information in the generated products (e.g., the API JAR file)
```

But to be 100% might be good if Wayne and/or Ivar approved this commit.

**Review by edbratt — APPROVED** [review]
I have no objections

**Pull request merged**
