### PR TITLE
Merge from release branch

### PR DESCRIPTION
**Pull request by arjantijms**
For administrative purposes

### CODE REVIEW

**Review by stuartwdouglas — CHANGES_REQUESTED** [review]
I don't think we want this do we? We should merge https://github.com/eclipse-ee4j/servlet-api/pull/361 instead to move master to 5.1, and have the 5.0.0 branch as 5.0.1-SNAPSHOT

**Comment by arjantijms** [comment]
@stuartwdouglas see "For administrative purposes". Once this PR is merged #361 can be merged. Merging the release branch for 5.0.0 is a requirement of the release process ;)

**Comment by stuartwdouglas** [comment]
Why? What purpose does it serve if it is going to be immediately overwritten? And even if it wasn't you then have 2 branches targetting 5.0.1-SNAPSHOT which is confusing.

**Comment by arjantijms** [comment]
> Why? What purpose does it serve if it is going to be immediately overwritten? 

Essentially to follow the completion steps here: https://github.com/eclipse-ee4j/servlet-api/issues/366

I'm not really sure how we handle the situation where the team refuses to carry out the last step, although I guess we have some leeway with the wording "as appropriate".

**Comment by stuartwdouglas** [comment]
Actually I just realised that this is coming from 5.0.0 and not 5.0, I missread it when I first looked at it. We need a 5.0 branch so maybe just merge this, then branch the 5.0 to tick of the last task checkbox, and I will just rebase my 5.1 PR.

**Review by stuartwdouglas — APPROVED** [review]

**Comment by stuartwdouglas** [comment]
Does it matter that the ECA agreement is failing for servlet-bot? I am guessing not?

**Comment by arjantijms** [comment]
Thanks!

The bot thing doesn't matter. It's a long standing annoyance though.

**Pull request merged**
