### PR TITLE
EE8 Renaming for #243

### PR DESCRIPTION
**Pull request by gregw**
Additional jakarta renaming changes for #243 

These may be too late for the actual release, but best to capture them for future releases.

Signed-off-by: Greg Wilkins <gregw@webtide.com>

### CODE REVIEW

**Comment by arjantijms** [comment]
@gregw Thanks for this PR. Do note there's still some more things that need to be changed, for instance the "Java EE" and 299/CDI references. For instance these:

https://github.com/eclipse-ee4j/servlet-api/blob/e0c4a31f5751faf8168bbcc259bd26d320abd556/api/src/main/java/javax/servlet/ServletContext.java#L632

**Comment by gregw** [comment]
@stuartwdouglas can I get a review from you too before merging.
@arjantijms can you do a PR for the EE references?

**Comment by arjantijms** [comment]
@gregw 
> @arjantijms can you do a PR for the EE references?

Sure, if this PR is merged I'll update my branch and make those changes. Thanks!

**Comment by gregw** [comment]
@stuartwdouglas nudge

**Pull request merged**
